# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# ghc 8.10.7
resolver: lts-18.10
# ghc 9.0.1
# resolver: nightly-2021-07-16

packages:
  - '.'
  - examples/

# nix:
#   enable: true
