# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# ghc 8.10.7
# resolver: lts-18.10
# ghc 9.6.1
resolver: lts-22.11
# ghc 9.8.1
# resolver: nightly-2024-02-22
packages:
  - '.'
  - examples/

# nix:
#   enable: true
